# Generated by Django 5.2.4 on 2025-10-13 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietGioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=1)),
                ('ngay_them', models.DateTimeField(auto_now_add=True)),
                ('ma_san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham')),
            ],
        ),
    ]
