# Generated by Django 5.2.4 on 2025-10-13 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('giohang', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='giohang',
            name='ma_nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chitietgiohang',
            name='ma_gio_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giohang.giohang'),
        ),
    ]
