# Generated by Django 5.2.7 on 2025-11-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giohang', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietgiohang',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chitietgiohang',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
