# Generated by Django 5.2.7 on 2025-11-11 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sanpham', '0002_sanpham_giakm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dat', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dia_chi_giao', models.CharField(default='', max_length=255)),
                ('phuong_thuc_thanh_toan', models.CharField(default='', max_length=50)),
                ('trang_thai_don_hang', models.CharField(choices=[('cho_xu_ly', 'Chờ xử lý'), ('dang_giao', 'Đang giao hàng'), ('da_giao', 'Đã giao'), ('da_huy', 'Đã hủy')], default='cho_xu_ly', max_length=20)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=1)),
                ('gia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('thanh_tien', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ma_san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham')),
                ('ma_don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='donhang.donhang')),
            ],
        ),
    ]
