# Generated by Django 5.2.4 on 2025-10-13 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dat', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_chi_giao', models.CharField(max_length=255)),
                ('phuong_thuc_thanh_toan', models.CharField(max_length=50)),
                ('trang_thai_don_hang', models.CharField(default='Đang xử lý', max_length=50)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thanh_tien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ma_san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham')),
            ],
        ),
    ]
