# Generated by Django 5.2.7 on 2025-10-15 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donhang', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietdonhang',
            name='ma_don_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='donhang.donhang'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='trang_thai_don_hang',
            field=models.CharField(choices=[('cho_xu_ly', 'Chờ xử lý'), ('dang_giao', 'Đang giao hàng'), ('da_giao', 'Đã giao'), ('da_huy', 'Đã hủy')], default='cho_xu_ly', max_length=20),
        ),
    ]
