# Generated by Django 5.2.4 on 2025-10-13 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('trang_thai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.CharField(max_length=200)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anh_dai_dien', models.ImageField(blank=True, null=True, upload_to='sanpham/')),
                ('trang_thai', models.BooleanField(default=True)),
                ('ma_danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.danhmuc')),
            ],
        ),
        migrations.CreateModel(
            name='BienTheSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kich_thuoc', models.CharField(blank=True, max_length=50, null=True)),
                ('mau_sac', models.CharField(blank=True, max_length=50, null=True)),
                ('so_luong', models.PositiveIntegerField(default=0)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='sanpham/')),
                ('ma_san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham')),
            ],
        ),
    ]
