# Generated by Django 5.2.7 on 2025-10-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nguoidung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='vai_tro',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('nhanvien', 'Nhân viên'), ('khachhang', 'Khách hàng')], default='khachhang', max_length=20),
        ),
    ]
